const apiList = [
    {
        name: "login",
        method: "POST",
        desc: "登录",
        path: "/members/user_address_login",
        mockPath: "/members/user_address_login",
        params: {
            address: "",
            message: "",
            signature: "",
        },
        options: {},
    },
    {
        name: "getInfo",
        method: "GET",
        desc: "登录",
        path: "/members/user_info",
        mockPath: "/members/user_info",
        params: {},
        options: {},
    },
    {
        name: "ownArts",
        method: "GET",
        desc: "获取所属作品集",
        path: "/arts/mine",
        mockPath: "/arts/mine",
        params: {},
        options: {},
    },
    {
        name: "postArt",
        method: "POST",
        desc: "上传艺术品",
        path: "/arts",
        mockPath: "/arts",
        params: {},
        options: {
            upload: [
                "img_main_file1",
                "img_main_file2",
                "img_main_file3",
                "img_detail_file1",
                "img_detail_file2",
                "img_detail_file3",
                "img_detail_file4",
                "img_detail_file5",
            ],
        },
    },
    {
        name: "postOrganization",
        method: "POST",
        desc: "注册机构",
        path: "/organizations",
        mockPath: "/organizations",
        params: {},
        options: {
            upload: ["img_file"],
        },
    },
    {
        name: "getSignedWorks",
        method: "GET",
        desc: "当前用户已签名作品",
        path: "/arts/my_signatures",
        mockPath: "/arts/my_signatures",
        params: {},
        options: {},
    },
    {
        name: "postApplySignature",
        method: "POST",
        desc: "申请其他机构签名",
        path: "/arts/{:id}/apply_signature",
        mockPath: "/arts/{:id}/apply_signature",
        params: {},
        options: {},
    },
    {
        name: "getApplySignature",
        method: "GET",
        desc: "申请签名列表",
        path: "/arts/applying_signatures",
        mockPath: "/arts/applying_signatures",
        params: {},
        options: {},
    },
];

export default apiList;
