const apiList = [
    {
        name: "login",
        method: "POST",
        desc: "登录",
        path: "/members/user_address_login",
        mockPath: "/members/user_address_login",
        params: {
            address: "",
            message: "",
            signature: "",
        },
        options: {},
    },
    {
        name: "getInfo",
        method: "GET",
        desc: "登录",
        path: "/members/user_info",
        mockPath: "/members/user_info",
        params: {},
        options: {},
    },
    {
        name: "ownArts",
        method: "GET",
        desc: "获取所属作品集",
        path: "/arts/mine",
        mockPath: "/arts/mine",
        params: {},
        options: {},
    },
    {
        name: "postArt",
        method: "POST",
        desc: "上传艺术品",
        path: "/arts",
        mockPath: "/arts",
        params: {},
        options: {
            upload: [
                "img_main_file1",
                "img_main_file2",
                "img_main_file3",
                "img_detail_file1",
                "img_detail_file2",
                "img_detail_file3",
                "img_detail_file4",
                "img_detail_file5",
            ],
        },
    },
    {
        name: "postOrganization",
        method: "POST",
        desc: "注册机构",
        path: "/organizations",
        mockPath: "/organizations",
        params: {},
        options: {
            upload: ["img_file"],
        },
    },
    {
        name: "getSignedWorks",
        method: "GET",
        desc: "当前用户已签名作品",
        path: "/arts/my_signatures",
        mockPath: "/arts/my_signatures",
        params: {},
        options: {},
    },
    {
        name: "postApplySignature",
        method: "POST",
        desc: "申请其他机构签名",
        path: "/arts/{:id}/apply_signature",
        mockPath: "/arts/{:id}/apply_signature",
        params: {},
        options: {},
    },
    {
        name: "getApplySignature",
        method: "GET",
        desc: "申请签名列表",
        path: "/arts/applying_signatures",
        mockPath: "/arts/applying_signatures",
        params: {},
        options: {},
    },
    {
        name: "postRefuseSignature",
        method: "POST",
        desc: "拒绝指定签名请求",
        path: "/arts/{:id}/reject_signature",
        mockPath: "/arts/{:id}/reject_signature",
        params: {
            organization_name: "",
        },
        options: {},
    },
    {
        name: "postChangeUserInfo",
        method: "POST",
        desc: "修改用户信息",
        path: "/members/change_user_info",
        mockPath: "/members/change_user_info",
        params: {
            avatar: "",
            recommend_image: "",
            display_name: "",
            desc: "",
            sex: "",
            artist_desc: "",
            real_name: "",
            phone_number: "",
            id_document_number: "",
        },
        options: {
            upload: ["avatar", "recommend_image"],
        },
    },
    {
        name: "getUserInfo",
        method: "GET",
        desc: "获取用户信息",
        path: "/members/user_info",
        mockPath: "/members/user_info",
        params: {},
        options: {},
    },
    {
        name: "getAuctionApplyList",
        method: "GET",
        desc: "获取申请拍卖会作品列表",
        path: "/auction_meetings/{:id}/applying_arts",
        mockPath: "/auction_meetings/{:id}/applying_arts",
        params: {},
        options: {},
    },
];

export default apiList;
